<a href="https://colab.research.google.com/github/mohamedalifaragitiai/NLP/blob/main/Session_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#!pip install nltk

In [5]:
from nltk.corpus import stopwords

In [6]:
from nltk.stem import PorterStemmer

In [7]:
from nltk.tokenize import TweetTokenizer

In [8]:
import nltk
nltk.download('twitter_samples')

[nltk_data] Downloading package twitter_samples to /root/nltk_data...
[nltk_data]   Unzipping corpora/twitter_samples.zip.


True

In [9]:
from nltk.corpus import twitter_samples

In [10]:
all_positive_tweets = twitter_samples.strings('positive_tweets.json')

In [11]:
all_negative_tweets = twitter_samples.strings('negative_tweets.json')

In [12]:
len(all_positive_tweets)

5000

In [13]:
len(all_positive_tweets)

5000

In [14]:
type(all_positive_tweets)

list

In [15]:
type(all_negative_tweets)

list

In [16]:
type(all_negative_tweets[0])

str

In [17]:
from nltk.tag.perceptron import random
all_positive_tweets[random.randint(0,5000)]

'@yvonneainah I love you! :)'

In [18]:
all_negative_tweets[random.randint(0,5000)]

'I want to ESCAPE please :('

In [19]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [20]:
from nltk.corpus import stopwords

In [21]:
from nltk.stem import PorterStemmer

In [22]:
from nltk.tokenize import TweetTokenizer

In [23]:
tweet = '''My beautiful sunflowers on a sunny Friday morning 
off :) #sunflowers #favourites #happy #Friday off... 
https://t.co/3tfYom0N1i'''

In [24]:
print(tweet)

My beautiful sunflowers on a sunny Friday morning 
off :) #sunflowers #favourites #happy #Friday off... 
https://t.co/3tfYom0N1i


Remove old style retweet text "RT"

In [25]:
import re

In [26]:
tweet2 = re.sub(r'^RT[\s]+', '', tweet)

Remove hyperlink

In [27]:
tweet2 = re.sub(r'https?:\/\/.*[\r]*', '', tweet2)

Remove hashtages, only removing the hash # sign from the word

In [28]:
tweet2 = re.sub(r'#', '', tweet2)

In [29]:
tweet2

'My beautiful sunflowers on a sunny Friday morning \noff :) sunflowers favourites happy Friday off... \n'

In [30]:
tweet2 = re.sub(r'\n', '', tweet2)

In [31]:
tweet2

'My beautiful sunflowers on a sunny Friday morning off :) sunflowers favourites happy Friday off... '

**split the tweets into array of words.**

In [32]:
from nltk import tokenize
#instantiate tokenizer class
tokenizer = TweetTokenizer(preserve_case=False, strip_handles=True, reduce_len=True)

In [33]:
#tokenize tweets
tweet_tokens = tokenizer.tokenize(tweet2)

In [34]:
print('Tokenized string: ', '\n', tweet_tokens)

Tokenized string:  
 ['my', 'beautiful', 'sunflowers', 'on', 'a', 'sunny', 'friday', 'morning', 'off', ':)', 'sunflowers', 'favourites', 'happy', 'friday', 'off', '...']


**To remove stop words and punctuation**

In [35]:
#import the English stop words list from NLTK
stopwords_english = stopwords.words('english')

In [36]:
stopwords_english

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [37]:
import string

In [38]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

** Now, we clean our tweet.**

In [39]:
tweets_clean = []

In [40]:
for word in tweet_tokens: #Go through every word in your tokens list
  if (word not in stopwords_english and #remove stopwords
      word not in string.punctuation): #remove punctuation
    tweets_clean.append(word)

In [41]:
print('Removed stop words and punctuations: ', '\n', tweets_clean)

Removed stop words and punctuations:  
 ['beautiful', 'sunflowers', 'sunny', 'friday', 'morning', ':)', 'sunflowers', 'favourites', 'happy', 'friday', '...']


**Stemming**


In [42]:
#Instantiate stemming class
stemmer = PorterStemmer()

#Create an empty list to store the stems
tweets_stem = []

for word in tweets_clean:
  stem_word = stemmer.stem(word) # stemming word
  tweets_stem.append(stem_word) # append to the list


In [43]:
print('stemmed words: ', '\n', tweets_stem)

stemmed words:  
 ['beauti', 'sunflow', 'sunni', 'friday', 'morn', ':)', 'sunflow', 'favourit', 'happi', 'friday', '...']


**Process Tweets**

In [44]:
def process_tweet(tweet):
  stemmer = PorterStemmer()
  stopwords_english = stopwords.words('english')
  #remove stock market trickers like $GE
  tweet = re.sub(r'\$\w*', '', tweet)
  #remove old style retweet text "RT"
  tweet = re.sub(r'^RT[\s]+', '', tweet)
  #remove hyperlinkes
  tweet = re.sub(r'https?:\/\/.*[\r\n]*', '', tweet)
  #to remove \n 
  tweet = re.sub(r'\n', '', tweet)
  tweet = re.sub(r'#', '', tweet)
  #tokenize tweets
  tokenizer = TweetTokenizer(preserve_case=False, strip_handles=True, reduce_len=True)
  tweet_tokens = tokenizer.tokenize(tweet)
  return tweet_tokens

**Feature Extraction** build the words frequency 
table.

In [45]:
import numpy as np

def build_freqs(tweets,ys):
  # convert np array to list scince zip needs an iterable.
  # the squeez is necessary or the list ends up with one element.
  # also note that this is just n NOP if ys is already a list.
  yslist = np.squeeze(ys).tolist()

  #start with an empty dictionary and populate it by looping over all tweets
  # and over all processed words in each tweet.
  freqs = {}
  for y, tweet in zip(yslist, tweets):
    for word in process_tweet(tweet):
      pair = (word, y)
      if pair in freqs:
        freqs[pair] += 1
      else:
        freqs[pair] = 1
  return freqs

**After getting the frequencies of all unique words, we extract the 
features vector for each tweet.**

In [46]:
def extract_features(tweet, freqs):
  # process tweet tokenizes, stems, and removes stopwords
  word_l = process_tweet(tweet)
  # 3 elements in the form of a 1 x 3 vector
  x = np.zeros((1,3))
  # bais term is set to 1
  x[0,0] = 1
  # loop through each word in the list of words 
  for word in word_l:
    # increment the word count for the positive label 1
    x[0,1] += freqs.get((word, 1.0),0)
    # increment the word count for the negative label 0
    x[0,2] += freqs.get((word, 0.0), 0)
  assert(x.shape == (1, 3))
  return x

#Prepare the data for our model.


In [47]:
#split the data into two pices, one for training and one for testing 

test_pos = all_positive_tweets[4000:]
train_pos = all_positive_tweets[:4000]

test_neg = all_negative_tweets[4000:]
train_neg = all_negative_tweets[:4000]

train_x = train_pos + train_neg 
test_x = test_pos + test_neg

train_y = np.append(np.ones((len(train_pos),1)), np.zeros((len(train_neg),1)), axis = 0)

test_y = np.append(np.ones((len(test_pos),1)), np.zeros((len(test_neg),1)), axis = 0)

**Build Frequencies dictionary for the training data.**

In [48]:
freqs = build_freqs(train_x, train_y)

In [49]:
print('type(freqs) = ' + str(type(freqs)))

type(freqs) = <class 'dict'>


In [50]:
print("len(freqs) = "+ str(len(freqs.keys())) )

len(freqs) = 13562


In [51]:
freqs

{('followfriday', 1.0): 23,
 ('for', 1.0): 606,
 ('being', 1.0): 49,
 ('top', 1.0): 29,
 ('engaged', 1.0): 7,
 ('members', 1.0): 10,
 ('in', 1.0): 381,
 ('my', 1.0): 441,
 ('community', 1.0): 25,
 ('this', 1.0): 241,
 ('week', 1.0): 61,
 (':)', 1.0): 2847,
 ('hey', 1.0): 59,
 ('james', 1.0): 7,
 ('!', 1.0): 1455,
 ('how', 1.0): 60,
 ('odd', 1.0): 1,
 (':/', 1.0): 5,
 ('please', 1.0): 77,
 ('call', 1.0): 21,
 ('our', 1.0): 111,
 ('contact', 1.0): 4,
 ('centre', 1.0): 1,
 ('on', 1.0): 242,
 ('02392441234', 1.0): 1,
 ('and', 1.0): 553,
 ('we', 1.0): 182,
 ('will', 1.0): 150,
 ('be', 1.0): 198,
 ('able', 1.0): 6,
 ('to', 1.0): 836,
 ('assist', 1.0): 1,
 ('you', 1.0): 1185,
 ('many', 1.0): 28,
 ('thanks', 1.0): 310,
 ('had', 1.0): 35,
 ('a', 1.0): 725,
 ('listen', 1.0): 8,
 ('last', 1.0): 36,
 ('night', 1.0): 49,
 ('as', 1.0): 82,
 ('bleed', 1.0): 2,
 ('is', 1.0): 353,
 ('an', 1.0): 98,
 ('amazing', 1.0): 39,
 ('track', 1.0): 5,
 ('.', 1.0): 984,
 ('when', 1.0): 69,
 ('are', 1.0): 152,
 ('s

**Extract your features vectors to use as input for the model.**

In [52]:
# collect the features 'x' and stack them into a  matrix X
X = np.zeros((len(train_x), 3))
for i in range(len(train_x)):
  X[i, :] = extract_features(train_x[i], freqs)

In [53]:
X

array([[1.0000e+00, 4.7200e+03, 1.6120e+03],
       [1.0000e+00, 9.7950e+03, 4.4950e+03],
       [1.0000e+00, 1.0336e+04, 5.0490e+03],
       ...,
       [1.0000e+00, 2.1240e+03, 4.4770e+03],
       [1.0000e+00, 1.9710e+03, 6.5940e+03],
       [1.0000e+00, 5.7830e+03, 1.0346e+04]])

In [54]:
import pandas as pd
X_df = pd.DataFrame(X)

In [55]:
X_df

0        1        2
0     1.0   4720.0   1612.0
1     1.0   9795.0   4495.0
2     1.0  10336.0   5049.0
3     1.0   2862.0      4.0
4     1.0   9593.0   4481.0
...   ...      ...      ...
7995  1.0    469.0   4309.0
7996  1.0   3810.0   5180.0
7997  1.0   2124.0   4477.0
7998  1.0   1971.0   6594.0
7999  1.0   5783.0  10346.0

[8000 rows x 3 columns]

In [56]:
X_df.to_csv('features_extracted.csv')

##Prepare your real output Y


In [57]:
# training labels corresponding to X
Y = train_y

In [58]:
Y

array([[1.],
       [1.],
       [1.],
       ...,
       [0.],
       [0.],
       [0.]])

###Prepare LR functions: Sigmoid

In [59]:
def sigmoid(z):
  return 1 / (1 + np.exp(-z))

#Prepare LR functions: Gradient descent

In [60]:
def gredientDescent(x, y, theta, alpha, num_iters):
  '''
  Input:
  x : matrix of features which is (m, n+1)
  y : corresponding labels of the input matrix x , dimensions (m, 1)
  theta : weight vector of dimension (n+1, 1)
  num_iters : number of iterations you want to train your model for 

  Output:
  J : the final coast
  theta : your final weight vector 
  ''' 
  #get 'm' , the number of rows in matrix x
  m = x.shape[0]
  for i in range(0, num_iters):
    #get z, the dot product of x and theta
    z = np.dot(x, theta)
    #get the sigmoid of z
    h = sigmoid(z)
    #calculate the cost function 
    J = (-1/m )* (np.dot(y.transpose(), np.log(h)) + np.dot((1-y).transpose(), np.log(1-h)))

    #update the weights theta
    theta = theta - (alpha / m) * np.dot(x.transpose(), (h-y))
  J = float(J)
  return J, theta



#Applying gradient descent


In [61]:
J, theta = gredientDescent(X,Y, np.zeros((3,1)), 1e-9, 1500)

In [62]:
print(f"The cost after training is {J:.8f}.")

The cost after training is 0.21937448.


In [64]:
print(f"The resulting vector of weights is {[round(t, 8) for t in np.squeeze(theta)]}")

The resulting vector of weights is [4e-08, 0.00055706, -0.00052673]


#function for predicting tweets


In [65]:
def predict_tweets(tweet, freqs, theta):
  '''
  Input:
  tweet : a string
  freqs : a dictionary corresponding to the frequencies of each tuple (word, label)
  theta : (3, 1) vector of weights 
  Output:
  y_pred: the probability of a tweet being positive or negative
  '''
  #extract the features of the tweet and store it into x
  x = extract_features(tweet, freqs)

  # make the prediction using x and theta 
  y_pred = sigmoid(np.dot(x, theta))

  return y_pred

# Prediction

In [66]:
tweets_to_predict = ['I am happy', 'I am sad', 'my name is Mohamed Ali']

In [67]:
for tweet in tweets_to_predict:
  print('%s -> %f' % (tweet, predict_tweets(tweet, freqs, theta)))

I am happy -> 0.408673
I am sad -> 0.379219
my name is Mohamed Ali -> 0.481480


#Testing the accuracy of the model

In [68]:
from nltk.tag.hmm import accuracy
def test_logistic_regression(test_x, test_y, freqs, theta):
  '''
  Input: 
      test_x: a list of tweets
      test_y: (m, 1) vector with the corresponding labels for the list of tweets
      freqs : a dictionary with the frequency of each pair or tuple
      theta : weight vector of dimension (3, 1)
  Output:
      accuracy: # of tweets classified correctly / total # tweets
  '''

  y_hat = []
  for tweet in test_x:
    y_pred = predict_tweets(tweet, freqs, theta)

    if y_pred > 0.5:
      y_hat.append(1)
    else:
      y_hat.append(0)
  accuracy = (y_hat == np.squeeze(test_y)).sum() // len(test_x)
  return accuracy

In [69]:
my_tweet = 'My name is Mohamed , I am a good Machine Learning Engineer'
print(process_tweet(my_tweet))

['my', 'name', 'is', 'mohamed', ',', 'i', 'am', 'a', 'good', 'machine', 'learning', 'engineer']


In [70]:
y_hat = predict_tweets(my_tweet, freqs, theta)

In [71]:
y_hat

array([[0.4491331]])

In [72]:
if y_hat > 0.5:
  print('Pos ')
else:
  print('Neg ')

Neg 
